# This configuration should allow you to train Wan 14b t2v on 512x512x81 sized videos (or varying aspect ratios of the same size), with 24GB VRAM.

# change this
output_dir = '/home/zhengtianyu/yaowangzi/diffusion-pipe/data/diffusion_pipe_training_runs/wp'
# and this
dataset = '/home/zhengtianyu/yaowangzi/style-ipa/examples/dataset_style1000.toml'

# training settings
epochs = 1000
micro_batch_size_per_gpu = 2
pipeline_stages = 1
gradient_accumulation_steps = 1
gradient_clipping = 1
warmup_steps = 10

# eval settings
eval_every_n_epochs = 1
eval_before_first_step = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1

# misc settings
save_every_n_epochs = 1
save_every_n_steps = 100
checkpoint_every_n_minutes = 60
activation_checkpointing = 'unsloth'
partition_method = 'parameters'
save_dtype = 'bfloat16'
caching_batch_size = 32
steps_per_print = 1
video_clip_mode = 'single_beginning'
blocks_to_swap = 0

[model]
type = 'wan'
ckpt_path = '/home/zhengtianyu/yaowangzi/Wan2.2-TI2V-5B'
dtype = 'bfloat16'
transformer_dtype = 'float8'
timestep_sample_method = 'logit_normal'

[adapter]
type = 'ip-adapter'
ipa_num_tokens = 128
rank = 32
dtype = 'bfloat16'
siglip_pooling=true

[optimizer]
type = 'AdamW8bitKahan'
lr = 2e-5
betas = [0.9, 0.99]
weight_decay = 0.01
stabilize = false
